config/routes.rb
Rails.application.routes.draw do
  resources :images

  root 'images#index'

end

app/models/image.rb
class Image < ActiveRecord::Base
  mount_uploader :file, FileUploader
  validates :file, presence: true
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  respond_to :html, :js
  def index
    @images = Image.paginate(:page => params[:page], :per_page => 2)

    respond_to do |format|
      format.html
      format.json
    end
  end
  def create
    @image = Image.new(image_params)
    @image.save
    redirect_to action: "index"
  end
  def new
    @image = Image.new
  end

  def show
    @image = Image.find(params[:id])
  end

  private
    def image_params
      params.require(:image).permit(:id, :title, :file, :remote_file_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/.#index.html.haml
ubear@arch.1734:1457780416

app/views/images/_form.html.erb
<%= form_for @image, remote: true, :authenticity_token => true do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <div id="file_field_wrap">
    <%= f.file_field :file %>
  </div>

  <%= f.submit %>
<% end %>

app/views/images/index.html.haml
#form-wrap{:style=>"display:none;"}
  #image-form
#image-wrap
  - @images.each do |image|
    = link_to image_path(image) do
      .image-instance
        %h4.image-title= image.title
        %div
        = image_tag(image.file_url, width:"475")
  %div
  = will_paginate @images

app/views/images/new.js.erb
$('#image-form').html("<%= j (render 'form') %>");
$('#form-wrap').slideDown(350);

app/views/images/show.html.haml
#image-wrap
  %h1.image-title= @image.title
  %div
  =image_tag(@image.file_url, width:"475")

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Quake
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true 
    = javascript_include_tag 'application', 'data-turbolinks-track' => true 
    = csrf_meta_tags 
  %body
    #page-wrap
      #menu
        = image_tag('face.jpg', size:"65x65", class:"circular")
        #button-holder
          = link_to 'Share image!', new_image_path,{class: 'add-image-button', remote: true}
      #form-wrap{:style=>"display:none;"}
        #image-form
      = yield